/*
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */


#ifndef COMMON_H
#define COMMON_H

enum MD_ALGO {
    MD_NONE     = -1,
    MD_MD4      = 0,
    MD_MD5      = 1,
    MD_RMD160   = 2,
    MD_SHA1     = 3,
    MD_SHA224   = 4,
    MD_SHA256   = 5,
    MD_SHA384   = 6,
    MD_SHA512   = 7,
    MD_SHA512_224   = 8,
    MD_SHA512_256   = 9,
    MD_SHA3_224 = 10,
    MD_SHA3_256 = 11,
    MD_SHA3_384 = 12,
    MD_SHA3_512 = 13,
    MD_SHAKE128 = 14,
    MD_SHAKE256 = 15,
    MD_STREEBOG256  = 16,
    MD_STREEBOG512  = 17
};

#endif // COMMON_H
